Update to build on macosx catalina
kerl/kerl pull request #355
Opened 2020-10-19 20:10 UTC by raghavkarol

Remove reference to xcodebuild and dependency on Xcode. It's not a good idea to depend on Xcode for building OTP with kerl since we only needed clang and friends that are part of Xcode command line tools.

Tested with this configuration.

- OSX 10.15.7
- OTP 21.3.8.4
- Xcode Command line Tools 12

2020-10-20 12:27 UTC, motobob approved these changes
YOHOO!

2020-10-20 12:28 UTC, motobob commented
@mrallen1 would be great to get this merged and out.

2020-10-20 16:37 UTC, mrallen1 requested changes
If we can get the changes done, I'll merge and release it. Thanks.

2020-10-20 16:37 UTC, mrallen1 commented on kerl
> +    if [ "$1" -ge 22 ] && [ "$1" -le 23 ]; then
As far as I can tell, this patch **only** applies to mac OS - can you put this in `maybe_patch_darwin()` function which is around line 651?

2020-10-20 16:37 UTC, mrallen1 commented on kerl
> +KERL_VERSION='2.0.1'
Please don't modify this - I do that myself when I roll a new release. Thanks.

2020-10-20 19:17 UTC, mrallen1 approved these changes

2020-10-20 19:18 UTC, mrallen1 commented
I'm going to wait for the tests to run and then I'll get this merged. Thanks!!

2020-10-20 19:18 UTC, raghavkarol commented
Thank you also, see you around :)

2020-10-21 02:03 UTC, merged

2020-10-21 02:11 UTC, mrallen1 commented
FYI @motobob @raghavkarol the `2.0.1` tag has been pushed to the repo or you can just pull for the update. Thanks again.